name: node
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
env:
    SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
    SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
jobs:
    node:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  check-latest: true
                  cache: 'npm'
            - name: Install node_modules
              run: npm ci
            - name: Run linter
              run: npm run lint
            - name: Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2.2.4
              with:
                  output: comment, report-markdown
                  test-script: npm run test
            - name: Build project
              run: npm run build
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: build
                  retention-days: 3
